package de.simonscholz.bot.telegram.entities;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import lombok.Data;

@Entity
@Data
public class DmiLocation {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	private int dmiId;

	private String label;

	private double longitude;

	private double latitude;

	private String country;

	private String country_code;

	public void setId(long id) {
		// The id should not be set by clients, there this method is not
		// generated by lombok
	}
}
