package de.simonscholz.bot.telegram.entities;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

import lombok.Data;

@Entity
@Data
public class Query {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	@ManyToOne
	private User user;

	private String message;

	private double longitude;

	private double latitude;
	
	private Date date;

	public void setId(long id) {
		// The id should not be set by clients, there this method is not
		// generated by lombok
	}
}
